import { jsPDF } from "jspdf";

const BRAND_GREEN = [26, 122, 60];
const TEXT_DARK   = [26, 26, 26];
const TEXT_GREY   = [85, 85, 85];
const TEXT_MUTED  = [136, 136, 136];
const BG_PALE     = [232, 245, 238];
const BORDER      = [232, 232, 227];

function addHeader(doc, title, subtitle) {
  // Green top bar
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, 210, 14, "F");

  // COREX wordmark
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text("COREX", 14, 9.5);

  // Date right-aligned
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(200, 230, 212);
  doc.text(new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }), 196, 9.5, { align: "right" });

  // Title block
  doc.setFillColor(...BG_PALE);
  doc.rect(0, 14, 210, 26, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...TEXT_DARK);
  doc.text(title, 14, 27);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_GREY);
    doc.text(subtitle, 14, 35);
  }

  return 50; // y position after header
}

function addFooter(doc, pageNum) {
  const pageH = doc.internal.pageSize.height;
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(14, pageH - 12, 196, pageH - 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...TEXT_MUTED);
  doc.text("Generated by COREX — Indian Marketing Intelligence", 14, pageH - 7);
  doc.text(`Page ${pageNum}`, 196, pageH - 7, { align: "right" });
}

function wrapAndWrite(doc, text, x, y, maxWidth, lineHeight = 6) {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

// ─── 1. Generate response PDF ────────────────────────────────────────────────
export function generateResponsePDF({ title, body, actionSteps = [], realExample = "", graphTitle = "" }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = addHeader(doc, title || "COREX Intelligence Report", "Marketing Strategy Output");

  // Body paragraphs
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(...TEXT_DARK);
  y = wrapAndWrite(doc, body || "", 14, y, 182, 6.5);
  y += 6;

  // Action Steps
  if (actionSteps.length > 0) {
    // Section label
    doc.setFillColor(...BG_PALE);
    doc.roundedRect(14, y, 182, 8, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...BRAND_GREEN);
    doc.text("ACTION STEPS", 18, y + 5.5);
    y += 13;

    actionSteps.forEach((step, i) => {
      // Number circle
      doc.setFillColor(...BRAND_GREEN);
      doc.circle(17.5, y - 1, 3, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(255, 255, 255);
      doc.text(String(i + 1), 17.5, y + 0.3, { align: "center" });

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_DARK);
      y = wrapAndWrite(doc, step, 24, y, 172, 6);
      y += 3;
    });
    y += 4;
  }

  // Real Example
  if (realExample) {
    doc.setDrawColor(...BRAND_GREEN);
    doc.setLineWidth(0.8);
    doc.line(14, y, 14, y + 22);
    doc.setFillColor(248, 252, 249);
    doc.rect(16, y, 180, 22, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...BRAND_GREEN);
    doc.text("REAL EXAMPLE", 20, y + 6);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_DARK);
    wrapAndWrite(doc, realExample, 20, y + 13, 172, 6);
    y += 30;
  }

  addFooter(doc, 1);
  doc.save(`corex-report-${Date.now()}.pdf`);
}

// ─── 2. Generate campaign brief PDF ─────────────────────────────────────────
export function generateCampaignBriefPDF({ brandName = "Brand", campaignName = "Campaign", objective, audience, message, channels = [], timeline, budget, kpis = [], influencerTiers = [] }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = addHeader(doc, `${campaignName}`, `Campaign Brief — ${brandName}`);

  const section = (label) => {
    doc.setFillColor(...BRAND_GREEN);
    doc.rect(14, y, 3, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...BRAND_GREEN);
    doc.text(label, 20, y + 5.5);
    y += 13;
  };

  const field = (label, value) => {
    if (!value) return;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(label.toUpperCase(), 14, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(...TEXT_DARK);
    y = wrapAndWrite(doc, value, 14, y, 182, 6.5);
    y += 6;
  };

  section("CAMPAIGN OVERVIEW");
  field("Objective", objective);
  field("Target Audience", audience);
  field("Core Message", message);
  field("Timeline", timeline);
  field("Budget", budget);

  if (channels.length > 0) {
    section("CHANNEL MIX");
    channels.forEach(ch => {
      doc.setFillColor(...BG_PALE);
      doc.roundedRect(14, y, 55, 10, 2, 2, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...TEXT_DARK);
      doc.text(ch, 18, y + 6.5);
      y += 14;
    });
    y += 4;
  }

  if (kpis.length > 0) {
    section("KEY PERFORMANCE INDICATORS");
    kpis.forEach((kpi, i) => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_DARK);
      doc.text(`${i + 1}. ${kpi}`, 14, y);
      y += 7;
    });
    y += 4;
  }

  if (influencerTiers.length > 0) {
    section("INFLUENCER STRATEGY");
    influencerTiers.forEach(tier => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(...TEXT_DARK);
      doc.text(tier.name || "", 14, y);
      if (tier.count) {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...TEXT_GREY);
        doc.text(`${tier.count} creators`, 100, y);
      }
      if (tier.budget) {
        doc.setTextColor(...BRAND_GREEN);
        doc.text(tier.budget, 182, y, { align: "right" });
      }
      y += 7;
    });
  }

  addFooter(doc, 1);
  doc.save(`corex-campaign-brief-${Date.now()}.pdf`);
}

// ─── 3. Generate content calendar PDF ───────────────────────────────────────
export function generateContentCalendarPDF({ brandName = "Brand", month = "", posts = [] }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = addHeader(doc, `Content Calendar${month ? ` — ${month}` : ""}`, `Created for ${brandName}`);

  const COLS = { date: 14, platform: 45, format: 80, hook: 115, status: 185 };
  const ROW_H = 12;

  // Table header
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(14, y, 182, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text("DATE",     COLS.date + 1, y + 5.5);
  doc.text("PLATFORM", COLS.platform + 1, y + 5.5);
  doc.text("FORMAT",   COLS.format + 1, y + 5.5);
  doc.text("HOOK / IDEA", COLS.hook + 1, y + 5.5);
  doc.text("STATUS",   COLS.status + 1, y + 5.5);
  y += 8;

  posts.forEach((post, i) => {
    if (y > 265) {
      addFooter(doc, doc.internal.getNumberOfPages());
      doc.addPage();
      y = 20;
    }

    // Alternating row background
    if (i % 2 === 0) {
      doc.setFillColor(248, 248, 246);
      doc.rect(14, y, 182, ROW_H, "F");
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...TEXT_DARK);
    doc.text(post.date || "", COLS.date + 1, y + 7.5);
    doc.text(post.platform || "", COLS.platform + 1, y + 7.5);
    doc.text(post.format || "", COLS.format + 1, y + 7.5);

    const hookLines = doc.splitTextToSize(post.hook || "", 65);
    doc.text(hookLines[0] || "", COLS.hook + 1, y + 7.5);

    // Status pill
    const statusColors = { Draft: [230, 230, 225], Scheduled: [224, 245, 232], Published: [232, 245, 238] };
    const sc = statusColors[post.status] || statusColors.Draft;
    doc.setFillColor(...sc);
    doc.roundedRect(COLS.status, y + 3, 24, 6, 1.5, 1.5, "F");
    doc.setFontSize(7.5);
    doc.setTextColor(...TEXT_DARK);
    doc.text(post.status || "Draft", COLS.status + 12, y + 7.5, { align: "center" });

    y += ROW_H;
  });

  // Row border lines
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.2);

  addFooter(doc, doc.internal.getNumberOfPages());
  doc.save(`corex-content-calendar-${Date.now()}.pdf`);
}
