import { jsPDF } from "jspdf";

// ── Design tokens ─────────────────────────────────────────────────────────────
const GREEN       = [26, 122, 60];
const GREEN_PALE  = [232, 245, 238];
const GREEN_MID   = [200, 230, 212];
const DARK        = [26, 26, 26];
const GREY        = [85, 85, 85];
const MUTED       = [150, 150, 150];
const LIGHT_BG    = [248, 252, 249];
const BORDER      = [232, 232, 227];
const ORANGE      = [249, 115, 22];
const BLUE        = [79, 156, 249];
const TEAL        = [20, 184, 166];
const PURPLE      = [168, 85, 247];
const PINK        = [244, 63, 94];
const YELLOW      = [234, 179, 8];

const BAR_COLORS = [ORANGE, TEAL, YELLOW, PURPLE, PINK, GREEN];
const PAGE_W = 210;
const PAGE_H = 297;
const M = 14;       // margin
const CW = PAGE_W - M * 2;  // content width

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Replace characters jsPDF built-in fonts can't render */
function cleanText(str = "") {
  return str
    .replace(/₹/g, "Rs.")
    .replace(/[""]/g, '"')
    .replace(/['']/g, "'")
    .replace(/—/g, " - ")
    .replace(/–/g, "-")
    .replace(/…/g, "...")
    .replace(/[^\x00-\x7F]/g, (c) => {
      // Keep common Indian punctuation, replace others with space
      return " ";
    });
}

/** Write wrapped text and return new Y. Adds page if needed. */
function write(doc, text, x, y, maxW, { size = 10.5, font = "normal", family = "helvetica", color = DARK, lineH = 6.2, pageBreakCb } = {}) {
  doc.setFont(family, font);
  doc.setFontSize(size);
  doc.setTextColor(...color);
  const lines = doc.splitTextToSize(cleanText(text), maxW);
  for (const line of lines) {
    if (pageBreakCb && y + lineH > PAGE_H - 18) y = pageBreakCb();
    doc.text(line, x, y);
    y += lineH;
  }
  return y;
}

function sectionBadge(doc, label, y) {
  doc.setFillColor(...GREEN);
  doc.rect(M, y, 3, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...GREEN);
  doc.text(label, M + 6, y + 5);
  return y + 12;
}

// ── Header & footer ───────────────────────────────────────────────────────────

function addHeader(doc, title, subtitle) {
  // Green top stripe
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, PAGE_W, 13, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(255, 255, 255);
  doc.text("COREX", M, 9);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(200, 230, 212);
  doc.text(new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }), PAGE_W - M, 9, { align: "right" });

  // Title block
  doc.setFillColor(...GREEN_PALE);
  doc.rect(0, 13, PAGE_W, 28, "F");

  // Title — truncated to fit
  const safeTitle = cleanText(title || "COREX Report");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...DARK);
  const titleLines = doc.splitTextToSize(safeTitle, CW);
  let ty = 25;
  titleLines.slice(0, 2).forEach(l => { doc.text(l, M, ty); ty += 8; });

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    doc.text(cleanText(subtitle), M, 38);
  }

  // Thin green rule under header
  doc.setDrawColor(...GREEN_MID);
  doc.setLineWidth(0.4);
  doc.line(M, 42, PAGE_W - M, 42);

  return 50;
}

function addFooter(doc, pageNum) {
  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.3);
  doc.line(M, PAGE_H - 12, PAGE_W - M, PAGE_H - 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text("Generated by COREX  |  corexnt.com", M, PAGE_H - 7);
  doc.text(`Page ${pageNum}`, PAGE_W - M, PAGE_H - 7, { align: "right" });
}

// ── 1. Response PDF ───────────────────────────────────────────────────────────

export function generateResponsePDF({ title, body, actionSteps = [], realExample = "", graphData = null, chartImage = null }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let pageNum = 1;

  const newPage = () => {
    addFooter(doc, pageNum);
    doc.addPage();
    pageNum++;
    // Minimal header on continuation pages
    doc.setFillColor(...GREEN);
    doc.rect(0, 0, PAGE_W, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text("COREX", M, 5.5);
    return 18;
  };

  const checkY = (y, needed = 20) => {
    if (y + needed > PAGE_H - 18) return newPage();
    return y;
  };

  let y = addHeader(doc, title, "Marketing Strategy Output — COREX Intelligence");

  // ── Body paragraphs ─────────────────────────────────────────────────────────
  const paras = (body || "").split(/\n\n+/).filter(p => p.trim());
  for (const para of paras) {
    const text = cleanText(para.trim());
    const lines = doc.splitTextToSize(text, CW);
    y = checkY(y, lines.length * 6.2 + 6);

    // Detect if this para looks like a subheading (short, no period, ends in ?)
    const isSubhead = text.length < 60 && !text.endsWith(".") && !text.startsWith("-");
    if (isSubhead && para === paras[0]) {
      // Skip — it's probably the title rephrased
    } else if (isSubhead && lines.length === 1) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...DARK);
      doc.text(text, M, y);
      y += 8;
    } else {
      y = write(doc, text, M, y, CW, { size: 10.5, lineH: 6.2, color: DARK, pageBreakCb: newPage });
      y += 5;
    }
  }

  // ── Chart ────────────────────────────────────────────────────────────────────
  if (chartImage) {
    y = checkY(y, 90);
    y += 4;
    y = sectionBadge(doc, "DATA VISUALISATION", y);

    // White chart box with border
    const chartH = 72;
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.4);
    doc.roundedRect(M, y, CW, chartH, 3, 3, "FD");

    // Chart title
    if (graphData?.title) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...GREY);
      doc.text(cleanText(graphData.title), M + CW / 2, y + 8, { align: "center" });
    }

    // Embed chart image
    try {
      doc.addImage(chartImage, "PNG", M + 4, y + 12, CW - 8, chartH - 16);
    } catch {}

    y += chartH + 10;

  } else if (graphData?.labels && graphData?.values?.length > 0) {
    // Fallback: draw a simple bar chart natively in PDF
    y = checkY(y, 80);
    y += 4;
    y = sectionBadge(doc, "DATA SNAPSHOT", y);

    const vals = graphData.values;
    const labels = graphData.labels;
    const maxVal = Math.max(...vals, 1);
    const chartAreaH = 52;
    const chartAreaY = y + 6;
    const barAreaW = CW - 8;
    const barW = Math.min(18, (barAreaW / vals.length) - 4);
    const barSpacing = barAreaW / vals.length;

    // Chart background
    doc.setFillColor(250, 252, 250);
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.3);
    doc.roundedRect(M, chartAreaY, CW, chartAreaH + 14, 3, 3, "FD");

    // Title
    if (graphData.title) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(...GREY);
      doc.text(cleanText(graphData.title), M + CW / 2, chartAreaY + 8, { align: "center" });
    }

    // Bars
    vals.forEach((val, i) => {
      const barH = (val / maxVal) * (chartAreaH - 16);
      const bx = M + 4 + i * barSpacing + (barSpacing - barW) / 2;
      const by = chartAreaY + chartAreaH - barH - 4;
      const c = BAR_COLORS[i % BAR_COLORS.length];
      doc.setFillColor(...c);
      doc.roundedRect(bx, by, barW, barH, 1.5, 1.5, "F");

      // Value above bar
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.setTextColor(...DARK);
      doc.text(String(val), bx + barW / 2, by - 2, { align: "center" });

      // Label below
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.5);
      doc.setTextColor(...GREY);
      const labelText = cleanText(labels[i] || "");
      const labelLines = doc.splitTextToSize(labelText, barSpacing - 2);
      labelLines.slice(0, 2).forEach((l, li) => {
        doc.text(l, bx + barW / 2, chartAreaY + chartAreaH + li * 4 + 2, { align: "center" });
      });
    });

    y = chartAreaY + chartAreaH + 20;
  }

  // ── Action Steps ─────────────────────────────────────────────────────────────
  if (actionSteps.length > 0) {
    y = checkY(y, 50);
    y += 4;
    y = sectionBadge(doc, "ACTION STEPS", y);

    for (let i = 0; i < actionSteps.length; i++) {
      const step = cleanText(stripForPDF(actionSteps[i]));
      const lines = doc.splitTextToSize(step, CW - 16);
      const blockH = lines.length * 6 + 10;
      y = checkY(y, blockH);

      // Number circle
      doc.setFillColor(...GREEN);
      doc.circle(M + 5, y + 3, 4, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(255, 255, 255);
      doc.text(String(i + 1), M + 5, y + 4.5, { align: "center" });

      // Step text
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      lines.forEach((l, li) => {
        doc.text(l, M + 13, y + (li === 0 ? 4.5 : 4.5 + li * 6));
      });

      // Connector line (except after last)
      if (i < actionSteps.length - 1) {
        doc.setDrawColor(...GREEN_MID);
        doc.setLineWidth(0.5);
        doc.setLineDashPattern([1, 2], 0);
        doc.line(M + 5, y + 7, M + 5, y + blockH - 2);
        doc.setLineDashPattern([], 0);
      }

      y += blockH;
    }
    y += 4;
  }

  // ── Real Example ─────────────────────────────────────────────────────────────
  if (realExample) {
    const exText = cleanText(stripForPDF(realExample));
    const exLines = doc.splitTextToSize(exText, CW - 10);
    const exH = exLines.length * 6.2 + 16;
    y = checkY(y, exH + 10);
    y += 4;
    y = sectionBadge(doc, "REAL EXAMPLE", y);

    // Left accent bar
    doc.setFillColor(...GREEN);
    doc.rect(M, y, 3, exH, "F");

    // Box background
    doc.setFillColor(...LIGHT_BG);
    doc.setDrawColor(...GREEN_MID);
    doc.setLineWidth(0.3);
    doc.rect(M + 3, y, CW - 3, exH, "FD");

    // Example text
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    exLines.forEach((l, li) => {
      doc.text(l, M + 8, y + 10 + li * 6.2);
    });

    y += exH + 6;
  }

  // ── Summary box (if nothing else) ────────────────────────────────────────────
  if (!actionSteps.length && !realExample && !chartImage && !graphData) {
    y = checkY(y, 28);
    doc.setFillColor(...GREEN_PALE);
    doc.roundedRect(M, y, CW, 20, 3, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...GREEN);
    doc.text("Powered by COREX — Indian Marketing Intelligence Engine", M + CW / 2, y + 9, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...GREY);
    doc.text("Ask follow-up questions in the app to generate a deeper strategy", M + CW / 2, y + 15, { align: "center" });
  }

  addFooter(doc, pageNum);
  doc.save(`corex-report-${Date.now()}.pdf`);
}

function stripForPDF(text = "") {
  return text
    .replace(/\*\*/g, "")
    .replace(/^#{1,6}\s*/gm, "")
    .trim();
}

// ── 2. Campaign Brief PDF ─────────────────────────────────────────────────────

export function generateCampaignBriefPDF({ brandName = "Brand", campaignName = "Campaign", objective, audience, message, channels = [], timeline, budget, kpis = [], influencerTiers = [] }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let pageNum = 1;

  const newPage = () => {
    addFooter(doc, pageNum);
    doc.addPage();
    pageNum++;
    doc.setFillColor(...GREEN);
    doc.rect(0, 0, PAGE_W, 8, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text("COREX", M, 5.5);
    return 18;
  };

  const checkY = (y, needed = 20) => {
    if (y + needed > PAGE_H - 18) return newPage();
    return y;
  };

  let y = addHeader(doc, campaignName, `Campaign Brief — ${brandName}`);

  const field = (label, value, y) => {
    if (!value) return y;
    y = checkY(y, 20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(cleanText(label).toUpperCase(), M, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(...DARK);
    const lines = doc.splitTextToSize(cleanText(value), CW);
    lines.forEach(l => {
      if (y + 7 > PAGE_H - 18) y = newPage();
      doc.text(l, M, y);
      y += 6.5;
    });
    return y + 5;
  };

  y = sectionBadge(doc, "CAMPAIGN OVERVIEW", y);
  y = field("Objective", objective, y);
  y = field("Target Audience", audience, y);
  y = field("Core Message", message, y);
  y = field("Timeline", timeline, y);
  y = field("Budget", budget, y);

  if (channels.length > 0) {
    y = checkY(y, 30);
    y = sectionBadge(doc, "CHANNEL MIX", y);
    const cols = 3;
    channels.forEach((ch, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      if (col === 0) y = checkY(y, 14);
      const cx = M + col * (CW / cols);
      doc.setFillColor(...GREEN_PALE);
      doc.roundedRect(cx, y - 4 + row * 14, CW / cols - 4, 11, 2, 2, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(...DARK);
      doc.text(cleanText(ch), cx + 5, y + 3.5 + row * 14);
      if (col === cols - 1 || i === channels.length - 1) { if (col === cols - 1) y += 14; }
    });
    y += 8;
  }

  if (kpis.length > 0) {
    y = checkY(y, 30);
    y = sectionBadge(doc, "KEY PERFORMANCE INDICATORS", y);
    kpis.forEach((kpi, i) => {
      y = checkY(y, 10);
      doc.setFillColor(...GREEN);
      doc.circle(M + 3, y - 1, 2, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...DARK);
      doc.text(cleanText(kpi), M + 8, y);
      y += 7;
    });
    y += 4;
  }

  if (influencerTiers.length > 0) {
    y = checkY(y, 40);
    y = sectionBadge(doc, "INFLUENCER STRATEGY", y);
    influencerTiers.forEach((tier) => {
      y = checkY(y, 12);
      doc.setFillColor(...GREEN_PALE);
      doc.roundedRect(M, y - 3, CW, 10, 2, 2, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(...DARK);
      doc.text(cleanText(tier.name || ""), M + 4, y + 3.5);
      if (tier.count) {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...GREY);
        doc.text(`${tier.count} creators`, M + 80, y + 3.5);
      }
      if (tier.budget) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...GREEN);
        doc.text(cleanText(tier.budget), PAGE_W - M - 4, y + 3.5, { align: "right" });
      }
      y += 12;
    });
  }

  addFooter(doc, pageNum);
  doc.save(`corex-campaign-brief-${Date.now()}.pdf`);
}

// ── 3. Content Calendar PDF ───────────────────────────────────────────────────

export function generateContentCalendarPDF({ brandName = "Brand", month = "", posts = [] }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let pageNum = 1;
  let y = addHeader(doc, `Content Calendar${month ? ` — ${month}` : ""}`, `Created for ${brandName}`);

  const ROW_H = 12;
  const COLS = { date: M, platform: M + 26, format: M + 56, hook: M + 86, status: PAGE_W - M - 24 };

  // Table header
  doc.setFillColor(...GREEN);
  doc.rect(M, y, CW, 9, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(255, 255, 255);
  [["DATE", COLS.date], ["PLATFORM", COLS.platform], ["FORMAT", COLS.format], ["HOOK / IDEA", COLS.hook], ["STATUS", COLS.status]].forEach(([label, x]) => {
    doc.text(label, x + 1.5, y + 6);
  });
  y += 9;

  posts.forEach((post, i) => {
    if (y + ROW_H > PAGE_H - 18) {
      addFooter(doc, pageNum);
      doc.addPage();
      pageNum++;
      y = 16;
      doc.setFillColor(...GREEN);
      doc.rect(M, y, CW, 9, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(255, 255, 255);
      [["DATE", COLS.date], ["PLATFORM", COLS.platform], ["FORMAT", COLS.format], ["HOOK / IDEA", COLS.hook], ["STATUS", COLS.status]].forEach(([label, x]) => {
        doc.text(label, x + 1.5, y + 6);
      });
      y += 9;
    }

    if (i % 2 === 0) {
      doc.setFillColor(248, 252, 249);
      doc.rect(M, y, CW, ROW_H, "F");
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...DARK);
    doc.text(cleanText(post.date || ""), COLS.date + 1.5, y + 7.5);
    doc.text(cleanText(post.platform || ""), COLS.platform + 1.5, y + 7.5);
    doc.text(cleanText(post.format || ""), COLS.format + 1.5, y + 7.5);
    const hookText = cleanText(post.hook || "").slice(0, 55) + (cleanText(post.hook || "").length > 55 ? "…" : "");
    doc.text(hookText, COLS.hook + 1.5, y + 7.5);

    const sc = { Draft: GREEN_PALE, Scheduled: [[224, 242, 254], [2, 132, 199]], Published: [GREEN_PALE, GREEN] }[post.status] || [GREEN_PALE, GREEN];
    doc.setFillColor(...(Array.isArray(sc[0]) ? sc[0] : sc));
    doc.roundedRect(COLS.status, y + 2.5, 22, 6.5, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...DARK);
    doc.text(post.status || "Draft", COLS.status + 11, y + 7, { align: "center" });

    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.2);
    doc.line(M, y + ROW_H, M + CW, y + ROW_H);
    y += ROW_H;
  });

  addFooter(doc, pageNum);
  doc.save(`corex-content-calendar-${Date.now()}.pdf`);
}
