import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";

const FONT = "'Instrument Sans', sans-serif";
const SERIF = "'Instrument Serif', serif";
const CREDITS_COST = 4;

function cleanResult(text) {
  return (text || "")
    .replace(/\*\*/g, "").replace(/\*/g, "")
    .replace(/^#{1,4}\s+/gm, "").replace(/^---+$/gm, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/—/g, "-").replace(/–/g, "-").trim();
}

function downloadPDF(text, title) {
  const doc = new jsPDF();
  const margin = 20, maxWidth = 170, lineHeight = 7;
  doc.setFont("helvetica", "bold"); doc.setFontSize(14);
  doc.text(title, margin, margin);
  doc.setFont("helvetica", "normal"); doc.setFontSize(11);
  let y = margin + 12;
  for (const para of text.split("\n")) {
    if (para.trim() === "") { y += lineHeight * 0.5; continue; }
    for (const line of doc.splitTextToSize(para.trim(), maxWidth)) {
      if (y > 272) { doc.addPage(); y = margin; }
      doc.text(line, margin, y); y += lineHeight;
    }
  }
  y += 8; if (y > 280) { doc.addPage(); y = margin + 8; }
  doc.setFontSize(8); doc.setTextColor(120, 120, 120);
  doc.text("Generated by COREX — Creative Intelligence Engine", margin + maxWidth / 2, y, { align: "center" });
  doc.save(`${title.replace(/\s+/g, "_")}.pdf`);
}

function Pill({ label, selected, onClick }) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        padding: "7px 16px",
        borderRadius: 100,
        fontSize: 13,
        fontFamily: FONT,
        fontWeight: 500,
        cursor: "pointer",
        transition: "all 0.15s",
        background: selected ? "rgba(156,252,175,0.12)" : "rgba(255,255,255,0.04)",
        border: selected ? "1px solid rgba(156,252,175,0.4)" : "1px solid rgba(255,255,255,0.1)",
        color: selected ? "#9CFCAF" : "rgba(255,255,255,0.6)",
      }}
    >
      {label}
    </button>
  );
}

function Label({ children }) {
  return (
    <label
      style={{
        display: "block",
        fontSize: 11,
        fontFamily: FONT,
        fontWeight: 600,
        color: "rgba(255,255,255,0.4)",
        letterSpacing: "1px",
        textTransform: "uppercase",
        marginBottom: 8,
      }}
    >
      {children}
    </label>
  );
}

const inputStyle = {
  width: "100%",
  padding: "12px 14px",
  borderRadius: 10,
  fontSize: 14,
  fontFamily: FONT,
  background: "rgba(255,255,255,0.05)",
  border: "1px solid rgba(255,255,255,0.08)",
  color: "#ffffff",
  outline: "none",
  boxSizing: "border-box",
  caretColor: "#9CFCAF",
};

const PLATFORMS = ["Instagram", "YouTube", "LinkedIn", "X/Twitter", "Website"];

export default function CompetitorAnalysis() {
  const navigate = useNavigate();

  const [competitor, setCompetitor] = useState("");
  const [industry, setIndustry] = useState("");
  const [platforms, setPlatforms] = useState([]);
  const [links, setLinks] = useState("");

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const togglePlatform = (p) => {
    setPlatforms((prev) =>
      prev.includes(p) ? prev.filter((x) => x !== p) : [...prev, p]
    );
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    if (!competitor.trim()) {
      setError("Brand / competitor name is required.");
      return;
    }

    const credits = parseInt(localStorage.getItem("corex_credits") || "0");
    if (credits < CREDITS_COST) {
      setError(`You need ${CREDITS_COST} credits for this. Top up to continue.`);
      return;
    }

    setLoading(true);
    localStorage.setItem("corex_credits", String(credits - CREDITS_COST));

    const prompt = `Analyze what ${competitor} is currently doing as a competitor. Give a structured breakdown — no asterisks, no markdown, plain structured text only.

Brand/Competitor: ${competitor}
Industry: ${industry || "Not specified"}
Platforms: ${platforms.length > 0 ? platforms.join(", ") : "Not specified"}
Links/Handles: ${links || "Not provided"}

Return in this EXACT structure (plain text, no asterisks):

AD PATTERNS:
[What type of ads they run, formats, messaging angles]

CONTENT FORMATS:
[What content types they post, frequency estimate, what performs best]

MESSAGING STYLE:
[Their brand voice, key messages, who they're talking to]

VISUAL STYLE:
[Colors, aesthetic, photography style, design language]

POSTING FREQUENCY:
[Estimated posts per week per platform]

PLATFORMS USED:
[Which platforms they're active on and how]

GAPS YOU CAN OWN:
[3 specific things they're NOT doing that you can claim]

YOUR MOVE:
[2 immediate actions to differentiate]`;

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [{ role: "user", content: prompt }],
          userType: "creator",
          conversationTurn: 2,
          userName: localStorage.getItem("corex_user_name") || "",
          brandName: localStorage.getItem("corex_brand_name") || "",
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "API error");
      const fullText = data.reply || "";
      if (!fullText) throw new Error("No response generated");
      setResult(cleanResult(fullText));

      try {
        const history = JSON.parse(localStorage.getItem("corex_history") || "[]");
        history.unshift({
          id: Date.now(),
          title: `Analysis: ${competitor}`,
          messages: [
            { role: "user", content: prompt },
            { role: "assistant", content: fullText },
          ],
          ts: Date.now(),
          type: "competitor-analysis",
        });
        localStorage.setItem("corex_history", JSON.stringify(history.slice(0, 50)));
      } catch { /* silent */ }

    } catch (err) {
      setError(
        err.message === "Failed to fetch"
          ? "Connection error — check your internet and try again."
          : err.message || "Something went wrong. Please try again."
      );
      localStorage.setItem(
        "corex_credits",
        String(parseInt(localStorage.getItem("corex_credits") || "0") + CREDITS_COST)
      );
    }

    setLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  };

  const handleStartOver = () => {
    setResult("");
    setError("");
    setCompetitor("");
    setIndustry("");
    setPlatforms([]);
    setLinks("");
  };

  return (
    <div
      className="page-enter"
      style={{
        flex: 1,
        overflowY: "auto",
        WebkitOverflowScrolling: "touch",
        padding: "40px 32px",
        maxWidth: 680,
        margin: "0 auto",
        width: "100%",
      }}
    >
      {/* Back button */}
      <button
        onClick={() => navigate("/app/competitors")}
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: 6,
          background: "none",
          border: "none",
          cursor: "pointer",
          fontFamily: FONT,
          fontSize: 13,
          color: "rgba(255,255,255,0.4)",
          padding: "0 0 28px 0",
          transition: "color 0.15s",
        }}
        onMouseEnter={(e) => (e.currentTarget.style.color = "#ffffff")}
        onMouseLeave={(e) => (e.currentTarget.style.color = "rgba(255,255,255,0.4)")}
      >
        ← Competitors
      </button>

      {/* Header */}
      <div style={{ marginBottom: 32 }}>
        <div style={{ fontSize: 32, marginBottom: 12 }}>◎</div>
        <h1
          style={{
            fontFamily: SERIF,
            fontStyle: "italic",
            fontSize: 32,
            color: "#ffffff",
            margin: "0 0 8px 0",
            fontWeight: 400,
          }}
        >
          Competitor Analysis
        </h1>
        <p style={{ fontFamily: FONT, fontSize: 14, color: "rgba(255,255,255,0.45)", margin: 0 }}>
          Map what they're doing. Find the gap.
        </p>
      </div>

      <AnimatePresence mode="wait">
        {!result ? (
          <motion.form
            key="form"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            onSubmit={handleSubmit}
            style={{ display: "flex", flexDirection: "column", gap: 20 }}
          >
            {/* Competitor name */}
            <div>
              <Label>Brand / Competitor Name *</Label>
              <input
                type="text"
                value={competitor}
                onChange={(e) => setCompetitor(e.target.value)}
                placeholder="e.g. Nike, Notion, your biggest rival..."
                required
                style={inputStyle}
              />
            </div>

            {/* Industry */}
            <div>
              <Label>Industry / Niche</Label>
              <input
                type="text"
                value={industry}
                onChange={(e) => setIndustry(e.target.value)}
                placeholder="e.g. Fashion, SaaS, Food & Beverage..."
                style={inputStyle}
              />
            </div>

            {/* Platforms */}
            <div>
              <Label>Platforms</Label>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {PLATFORMS.map((p) => (
                  <Pill
                    key={p}
                    label={p}
                    selected={platforms.includes(p)}
                    onClick={() => togglePlatform(p)}
                  />
                ))}
              </div>
            </div>

            {/* Links / handles */}
            <div>
              <Label>Links / Handles (optional)</Label>
              <input
                type="text"
                value={links}
                onChange={(e) => setLinks(e.target.value)}
                placeholder="@handle or https://..."
                style={inputStyle}
              />
            </div>

            {error && (
              <p style={{ color: "#f87171", fontFamily: FONT, fontSize: 13, margin: 0 }}>{error}</p>
            )}

            <motion.button
              whileHover={{ translateY: -1 }}
              whileTap={{ scale: 0.98 }}
              type="submit"
              disabled={loading}
              style={{
                padding: "13px",
                borderRadius: 12,
                fontSize: 14,
                fontFamily: FONT,
                fontWeight: 600,
                background: loading
                  ? "rgba(255,255,255,0.05)"
                  : "linear-gradient(135deg, #9CFCAF, #226FF7)",
                color: loading ? "rgba(255,255,255,0.3)" : "#000",
                border: "none",
                cursor: loading ? "not-allowed" : "pointer",
                transition: "all 0.2s",
              }}
            >
              {loading ? "Analysing…" : `Run Competitor Analysis — ${CREDITS_COST} credits →`}
            </motion.button>
          </motion.form>
        ) : (
          <motion.div
            key="result"
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
          >
            <textarea
              value={result}
              onChange={(e) => setResult(e.target.value)}
              style={{
                width: "100%",
                minHeight: 480,
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 16,
                padding: "28px",
                fontFamily: FONT,
                fontSize: 14,
                color: "rgba(255,255,255,0.85)",
                lineHeight: 1.8,
                whiteSpace: "pre-wrap",
                marginBottom: 16,
                resize: "vertical",
                outline: "none",
                boxSizing: "border-box",
                caretColor: "#9CFCAF",
              }}
            />

            {/* Action buttons */}
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleCopy}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: copied ? "rgba(156,252,175,0.12)" : "rgba(255,255,255,0.06)",
                  border: copied ? "1px solid rgba(156,252,175,0.3)" : "1px solid rgba(255,255,255,0.1)",
                  color: copied ? "#9CFCAF" : "#ffffff",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                {copied ? "Copied!" : "Copy result"}
              </motion.button>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => downloadPDF(result, `Competitor Analysis — ${competitor}`)}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: "rgba(255,255,255,0.04)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  color: "rgba(255,255,255,0.7)",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                Save as PDF
              </motion.button>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleStartOver}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  color: "rgba(255,255,255,0.6)",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                Start over
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
