import { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";

const FONT = "'Instrument Sans', sans-serif";
const SERIF = "'Instrument Serif', serif";
const CREDITS_COST = 5;

function cleanResult(text) {
  return (text || "")
    .replace(/\*\*/g, "").replace(/\*/g, "")
    .replace(/^#{1,4}\s+/gm, "").replace(/^---+$/gm, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").trim();
}

function downloadPDF(text, title) {
  const doc = new jsPDF();
  const margin = 20, maxWidth = 170, lineHeight = 7;
  doc.setFont("helvetica", "bold"); doc.setFontSize(14);
  doc.text(title, margin, margin);
  doc.setFont("helvetica", "normal"); doc.setFontSize(11);
  let y = margin + 12;
  for (const para of text.split("\n")) {
    if (para.trim() === "") { y += lineHeight * 0.5; continue; }
    for (const line of doc.splitTextToSize(para.trim(), maxWidth)) {
      if (y > 272) { doc.addPage(); y = margin; }
      doc.text(line, margin, y); y += lineHeight;
    }
  }
  y += 8; if (y > 280) { doc.addPage(); y = margin + 8; }
  doc.setFontSize(8); doc.setTextColor(120, 120, 120);
  doc.text("Generated by COREX — Creative Intelligence Engine", margin + maxWidth / 2, y, { align: "center" });
  doc.save(`${title.replace(/\s+/g, "_")}.pdf`);
}

function Pill({ label, selected, onClick }) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        padding: "7px 16px",
        borderRadius: 100,
        fontSize: 13,
        fontFamily: FONT,
        fontWeight: 500,
        cursor: "pointer",
        transition: "all 0.15s",
        background: selected ? "rgba(156,252,175,0.12)" : "rgba(255,255,255,0.04)",
        border: selected ? "1px solid rgba(156,252,175,0.4)" : "1px solid rgba(255,255,255,0.1)",
        color: selected ? "#9CFCAF" : "rgba(255,255,255,0.6)",
      }}
    >
      {label}
    </button>
  );
}

function Label({ children }) {
  return (
    <label
      style={{
        display: "block",
        fontSize: 11,
        fontFamily: FONT,
        fontWeight: 600,
        color: "rgba(255,255,255,0.4)",
        letterSpacing: "1px",
        textTransform: "uppercase",
        marginBottom: 8,
      }}
    >
      {children}
    </label>
  );
}

const inputStyle = {
  width: "100%",
  padding: "12px 14px",
  borderRadius: 10,
  fontSize: 14,
  fontFamily: FONT,
  background: "rgba(255,255,255,0.05)",
  border: "1px solid rgba(255,255,255,0.08)",
  color: "#ffffff",
  outline: "none",
  boxSizing: "border-box",
  caretColor: "#9CFCAF",
};

const DURATIONS = ["2 hours", "4 hours", "6 hours", "Full Day"];

export default function ShootDaySystem() {
  const navigate = useNavigate();
  const fileRef = useRef(null);

  const [idea, setIdea] = useState("");
  const [duration, setDuration] = useState("4 hours");
  const [looks, setLooks] = useState("");
  const [scriptFile, setScriptFile] = useState(null);
  const [fileContent, setFileContent] = useState("");

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const handleFileChange = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setScriptFile(file);
    const isTxt = file.name.endsWith(".txt");
    if (isTxt) {
      const reader = new FileReader();
      reader.onload = (ev) => setFileContent(ev.target.result);
      reader.readAsText(file);
    } else {
      setFileContent("");
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    if (!idea.trim()) {
      setError("Shoot idea is required.");
      return;
    }

    const credits = parseInt(localStorage.getItem("corex_credits") || "0");
    if (credits < CREDITS_COST) {
      setError(`You need ${CREDITS_COST} credits for this. Top up to continue.`);
      return;
    }

    setLoading(true);
    localStorage.setItem("corex_credits", String(credits - CREDITS_COST));

    const scriptNote = scriptFile && !fileContent
      ? `Script/Brief file: ${scriptFile.name} (attached)`
      : "";

    const prompt = `You are a professional shoot director creating a complete shoot day system.

Shoot: ${idea}
Duration: ${duration}
Looks/Setups: ${looks || "Not specified"}
${fileContent ? `Script/Brief: ${fileContent}` : scriptNote}

Create a complete shoot day system — plain text, no asterisks, no markdown.

SHOT PRIORITY LIST:

MUST HAVE (Critical):
[List key shots — these cannot be missed]

GOOD TO HAVE (Secondary):
[Variations and supporting shots]

OPTIONAL (If time allows):
[Experimental or bonus shots]

TIMELINE:
[Break the ${duration} into segments with what to shoot]
0:00 — Setup and prep
[Continue timeline in 30min blocks]

SHOT BY SHOT PLAN:
[For each key shot: angle, movement, framing, what to capture]

ON-SET INSTRUCTIONS:
[Lighting notes, positioning, transitions between shots]

CRITICAL REMINDERS:
[5 things to never forget on set]

END OF DAY CHECKLIST:
[What to verify before wrapping]`;

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [{ role: "user", content: prompt }],
          userType: "creator",
          conversationTurn: 2,
          userName: localStorage.getItem("corex_user_name") || "",
          brandName: localStorage.getItem("corex_brand_name") || "",
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "API error");
      const fullText = data.reply || "";
      if (!fullText) throw new Error("No response generated");
      setResult(cleanResult(fullText));

      try {
        const history = JSON.parse(localStorage.getItem("corex_history") || "[]");
        history.unshift({
          id: Date.now(),
          title: `Shoot Day: ${idea.slice(0, 40)}`,
          messages: [
            { role: "user", content: prompt },
            { role: "assistant", content: fullText },
          ],
          ts: Date.now(),
          type: "directors-shoot-day",
        });
        localStorage.setItem("corex_history", JSON.stringify(history.slice(0, 50)));
      } catch { /* silent */ }

    } catch (err) {
      setError(
        err.message === "Failed to fetch"
          ? "Connection error — check your internet and try again."
          : err.message || "Something went wrong. Please try again."
      );
      localStorage.setItem(
        "corex_credits",
        String(parseInt(localStorage.getItem("corex_credits") || "0") + CREDITS_COST)
      );
    }

    setLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  };

  const handleStartOver = () => {
    setResult("");
    setError("");
    setIdea("");
    setDuration("4 hours");
    setLooks("");
    setScriptFile(null);
    setFileContent("");
  };

  return (
    <div
      className="page-enter"
      style={{
        flex: 1,
        overflowY: "auto",
        WebkitOverflowScrolling: "touch",
        padding: "40px 32px",
        maxWidth: 680,
        margin: "0 auto",
        width: "100%",
      }}
    >
      {/* Back button */}
      <button
        onClick={() => navigate("/app/directors")}
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: 6,
          background: "none",
          border: "none",
          cursor: "pointer",
          fontFamily: FONT,
          fontSize: 13,
          color: "rgba(255,255,255,0.4)",
          padding: "0 0 28px 0",
          transition: "color 0.15s",
        }}
        onMouseEnter={(e) => (e.currentTarget.style.color = "#ffffff")}
        onMouseLeave={(e) => (e.currentTarget.style.color = "rgba(255,255,255,0.4)")}
      >
        ← Directors
      </button>

      {/* Header */}
      <div style={{ marginBottom: 32 }}>
        <div style={{ fontSize: 32, marginBottom: 12 }}>🎬</div>
        <h1
          style={{
            fontFamily: SERIF,
            fontStyle: "italic",
            fontSize: 32,
            color: "#ffffff",
            margin: "0 0 8px 0",
            fontWeight: 400,
          }}
        >
          Shoot Day System
        </h1>
        <p style={{ fontFamily: FONT, fontSize: 14, color: "rgba(255,255,255,0.45)", margin: 0 }}>
          Shot list. Timeline. On-set guide.
        </p>
      </div>

      <AnimatePresence mode="wait">
        {!result ? (
          <motion.form
            key="form"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            onSubmit={handleSubmit}
            style={{ display: "flex", flexDirection: "column", gap: 20 }}
          >
            {/* Shoot idea */}
            <div>
              <Label>Shoot idea / description *</Label>
              <textarea
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                placeholder="What are you shooting? Product, fashion, film, content..."
                rows={3}
                required
                style={{ ...inputStyle, resize: "vertical" }}
              />
            </div>

            {/* Duration */}
            <div>
              <Label>Duration</Label>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {DURATIONS.map((d) => (
                  <Pill
                    key={d}
                    label={d}
                    selected={duration === d}
                    onClick={() => setDuration(d)}
                  />
                ))}
              </div>
            </div>

            {/* Script/brief upload */}
            <div>
              <Label>Upload script or brief (optional)</Label>
              <div
                onClick={() => fileRef.current?.click()}
                style={{
                  border: "1px dashed rgba(255,255,255,0.15)",
                  borderRadius: 10,
                  padding: "18px",
                  cursor: "pointer",
                  textAlign: "center",
                  transition: "border-color 0.15s",
                  background: "rgba(255,255,255,0.02)",
                }}
                onMouseEnter={(e) => (e.currentTarget.style.borderColor = "rgba(156,252,175,0.3)")}
                onMouseLeave={(e) => (e.currentTarget.style.borderColor = "rgba(255,255,255,0.15)")}
              >
                <p style={{ fontFamily: FONT, fontSize: 13, color: "rgba(255,255,255,0.4)", margin: 0 }}>
                  {scriptFile ? scriptFile.name : "Upload script or brief (.pdf, .doc, .docx, .txt)"}
                </p>
              </div>
              <input
                ref={fileRef}
                type="file"
                accept=".pdf,.doc,.docx,.txt"
                onChange={handleFileChange}
                style={{ display: "none" }}
              />
            </div>

            {/* Number of looks */}
            <div>
              <Label>Number of looks / setups</Label>
              <input
                type="text"
                value={looks}
                onChange={(e) => setLooks(e.target.value)}
                placeholder="e.g. 3 outfits, 5 scenes..."
                style={inputStyle}
              />
            </div>

            {error && (
              <p style={{ color: "#f87171", fontFamily: FONT, fontSize: 13, margin: 0 }}>{error}</p>
            )}

            <motion.button
              whileHover={{ translateY: -1 }}
              whileTap={{ scale: 0.98 }}
              type="submit"
              disabled={loading}
              style={{
                padding: "13px",
                borderRadius: 12,
                fontSize: 14,
                fontFamily: FONT,
                fontWeight: 600,
                background: loading
                  ? "rgba(255,255,255,0.05)"
                  : "linear-gradient(135deg, #9CFCAF, #226FF7)",
                color: loading ? "rgba(255,255,255,0.3)" : "#000",
                border: "none",
                cursor: loading ? "not-allowed" : "pointer",
                transition: "all 0.2s",
              }}
            >
              {loading ? "Building system…" : `Build Shoot Day System — ${CREDITS_COST} credits →`}
            </motion.button>
          </motion.form>
        ) : (
          <motion.div
            key="result"
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
          >
            <textarea
              value={result}
              onChange={(e) => setResult(e.target.value)}
              style={{
                width: "100%",
                minHeight: 480,
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 16,
                padding: "28px",
                fontFamily: FONT,
                fontSize: 14,
                color: "rgba(255,255,255,0.85)",
                lineHeight: 1.8,
                whiteSpace: "pre-wrap",
                marginBottom: 16,
                resize: "vertical",
                outline: "none",
                boxSizing: "border-box",
                caretColor: "#9CFCAF",
              }}
            />

            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleCopy}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: copied ? "rgba(156,252,175,0.12)" : "rgba(255,255,255,0.06)",
                  border: copied ? "1px solid rgba(156,252,175,0.3)" : "1px solid rgba(255,255,255,0.1)",
                  color: copied ? "#9CFCAF" : "#ffffff",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                {copied ? "Copied!" : "Copy result"}
              </motion.button>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => downloadPDF(result, "Shoot Day System")}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: "rgba(255,255,255,0.04)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  color: "rgba(255,255,255,0.7)",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                Save as PDF
              </motion.button>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleStartOver}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  color: "rgba(255,255,255,0.6)",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                Start over
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
