import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";

const FONT = "'Instrument Sans', sans-serif";
const SERIF = "'Instrument Serif', serif";
const CREDITS_COST = 5;

function cleanResult(text) {
  return (text || "")
    .replace(/\*\*/g, "").replace(/\*/g, "")
    .replace(/^#{1,4}\s+/gm, "").replace(/^---+$/gm, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/—/g, "-").replace(/–/g, "-").trim();
}

function downloadPDF(text, title) {
  const doc = new jsPDF();
  const margin = 20, maxWidth = 170, lineHeight = 7;
  doc.setFont("helvetica", "bold"); doc.setFontSize(14);
  doc.text(title, margin, margin);
  doc.setFont("helvetica", "normal"); doc.setFontSize(11);
  let y = margin + 12;
  for (const para of text.split("\n")) {
    if (para.trim() === "") { y += lineHeight * 0.5; continue; }
    for (const line of doc.splitTextToSize(para.trim(), maxWidth)) {
      if (y > 272) { doc.addPage(); y = margin; }
      doc.text(line, margin, y); y += lineHeight;
    }
  }
  y += 8; if (y > 280) { doc.addPage(); y = margin + 8; }
  doc.setFontSize(8); doc.setTextColor(120, 120, 120);
  doc.text("Generated by COREX — Creative Intelligence Engine", margin + maxWidth / 2, y, { align: "center" });
  doc.save(`${title.replace(/\s+/g, "_")}.pdf`);
}

function Pill({ label, selected, onClick }) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        padding: "7px 16px",
        borderRadius: 100,
        fontSize: 13,
        fontFamily: FONT,
        fontWeight: 500,
        cursor: "pointer",
        transition: "all 0.15s",
        background: selected ? "rgba(156,252,175,0.12)" : "rgba(255,255,255,0.04)",
        border: selected ? "1px solid rgba(156,252,175,0.4)" : "1px solid rgba(255,255,255,0.1)",
        color: selected ? "#9CFCAF" : "rgba(255,255,255,0.6)",
      }}
    >
      {label}
    </button>
  );
}

function Label({ children }) {
  return (
    <label
      style={{
        display: "block",
        fontSize: 11,
        fontFamily: FONT,
        fontWeight: 600,
        color: "rgba(255,255,255,0.4)",
        letterSpacing: "1px",
        textTransform: "uppercase",
        marginBottom: 8,
      }}
    >
      {children}
    </label>
  );
}

const inputStyle = {
  width: "100%",
  padding: "12px 14px",
  borderRadius: 10,
  fontSize: 14,
  fontFamily: FONT,
  background: "rgba(255,255,255,0.05)",
  border: "1px solid rgba(255,255,255,0.08)",
  color: "#ffffff",
  outline: "none",
  boxSizing: "border-box",
  caretColor: "#9CFCAF",
};

const PROJECT_TYPES = ["Campaign", "Shoot", "Brand", "Content", "Launch", "Event", "Other"];
const COMPLEXITIES = ["Simple", "Moderate", "Deep"];

export default function FlowSystem() {
  const navigate = useNavigate();

  const [projectName, setProjectName] = useState("");
  const [projectType, setProjectType] = useState("Campaign");
  const [deadline, setDeadline] = useState("");
  const [complexity, setComplexity] = useState("Moderate");
  const [budget, setBudget] = useState("");

  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    if (!projectName.trim()) {
      setError("Project name is required.");
      return;
    }

    const credits = parseInt(localStorage.getItem("corex_credits") || "0");
    if (credits < CREDITS_COST) {
      setError(`You need ${CREDITS_COST} credits for this. Top up to continue.`);
      return;
    }

    setLoading(true);
    localStorage.setItem("corex_credits", String(credits - CREDITS_COST));

    const today = new Date().toISOString().split("T")[0];

    const prompt = `You are COREX Flow — a creative project planning system. Generate a complete execution flow for this project.

Project: ${projectName}
Type: ${projectType}
Deadline: ${deadline || "Not specified"}
Complexity: ${complexity}
Budget: ${budget || "Not specified"}
Today's Date: ${today}

Generate a complete creative flow system — plain text only, no asterisks, no markdown.

FLOW OVERVIEW:
Total Days: [X days until deadline]
Daily Hours Needed: [X hours/day]
Complexity Score: [X/10]
Feasibility: [Green / Amber / Red] — [one sentence why]

PHASES:

PHASE 1 — THINKING (Day 1 to Day X):
Duration: X days
Focus: [What to think about]
Key outputs: [What you produce in this phase]
Avoid: [Common mistakes]

PHASE 2 — RESEARCH (Day X to Day X):
Duration: X days
Focus: [What to research]
Key outputs: [What you produce]
Avoid: [Common mistakes]

PHASE 3 — STRUCTURE (Day X to Day X):
Duration: X days
Focus: [What to structure/plan]
Key outputs: [What you produce]
Avoid: [Common mistakes]

PHASE 4 — EXECUTION (Day X to Day X):
Duration: X days
Focus: [What to execute]
Key outputs: [What you produce]
Avoid: [Common mistakes]

PHASE 5 — REFINEMENT (Day X to Day X):
Duration: X days
Focus: [What to refine/polish]
Key outputs: [What you produce]
Avoid: [Common mistakes]

DAILY FOCUS (WHAT TO DO TODAY):
[Based on today's date vs deadline, which phase are you in?]
Today's Focus: [Specific task]
Time Block: [X hours]
One Goal: [The single thing to complete today]

CALENDAR BREAKDOWN:
[Week by week — what happens each week]
Week 1: [Focus]
Week 2: [Focus]
[Continue as needed]

INSIGHTS:
Time Balance Score: X/10
Focus Score: X/10
Risk: [One key risk and mitigation]
Win Condition: [What does success look like]`;

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [{ role: "user", content: prompt }],
          userType: "creator",
          conversationTurn: 2,
          userName: localStorage.getItem("corex_user_name") || "",
          brandName: localStorage.getItem("corex_brand_name") || "",
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "API error");
      const fullText = data.reply || "";
      if (!fullText) throw new Error("No response generated");
      setResult(cleanResult(fullText));

      try {
        const history = JSON.parse(localStorage.getItem("corex_history") || "[]");
        history.unshift({
          id: Date.now(),
          title: `Flow: ${projectName}`,
          messages: [
            { role: "user", content: prompt },
            { role: "assistant", content: fullText },
          ],
          ts: Date.now(),
          type: "flow-system",
        });
        localStorage.setItem("corex_history", JSON.stringify(history.slice(0, 50)));
      } catch { /* silent */ }

    } catch (err) {
      setError(
        err.message === "Failed to fetch"
          ? "Connection error — check your internet and try again."
          : err.message || "Something went wrong. Please try again."
      );
      localStorage.setItem(
        "corex_credits",
        String(parseInt(localStorage.getItem("corex_credits") || "0") + CREDITS_COST)
      );
    }

    setLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  };

  const handleStartOver = () => {
    setResult("");
    setError("");
    setProjectName("");
    setProjectType("Campaign");
    setDeadline("");
    setComplexity("Moderate");
    setBudget("");
  };

  return (
    <div
      className="page-enter"
      style={{
        flex: 1,
        overflowY: "auto",
        WebkitOverflowScrolling: "touch",
        padding: "40px 32px",
        maxWidth: 680,
        margin: "0 auto",
        width: "100%",
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: 32 }}>
        <span
          style={{
            display: "inline-block",
            background: "rgba(255,255,255,0.06)",
            border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 100,
            padding: "4px 14px",
            fontSize: 12,
            fontFamily: FONT,
            color: "rgba(255,255,255,0.5)",
            marginBottom: 16,
          }}
        >
          📅 Flow System
        </span>
        <h1
          style={{
            fontFamily: SERIF,
            fontStyle: "italic",
            fontSize: 32,
            color: "#ffffff",
            margin: "0 0 8px 0",
            fontWeight: 400,
          }}
        >
          Flow System
        </h1>
        <p style={{ fontFamily: FONT, fontSize: 14, color: "rgba(255,255,255,0.45)", margin: 0 }}>
          Turn any project into a clear, daily execution plan.
        </p>
      </div>

      <AnimatePresence mode="wait">
        {!result ? (
          <motion.form
            key="form"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            onSubmit={handleSubmit}
            style={{ display: "flex", flexDirection: "column", gap: 20 }}
          >
            {/* Project name */}
            <div>
              <Label>Project name *</Label>
              <input
                type="text"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                placeholder="What are you building?"
                required
                style={inputStyle}
              />
            </div>

            {/* Project type */}
            <div>
              <Label>Project type</Label>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {PROJECT_TYPES.map((pt) => (
                  <Pill
                    key={pt}
                    label={pt}
                    selected={projectType === pt}
                    onClick={() => setProjectType(pt)}
                  />
                ))}
              </div>
            </div>

            {/* Deadline */}
            <div>
              <Label>Deadline</Label>
              <input
                type="date"
                value={deadline}
                onChange={(e) => setDeadline(e.target.value)}
                style={{
                  ...inputStyle,
                  colorScheme: "dark",
                }}
              />
            </div>

            {/* Complexity */}
            <div>
              <Label>Complexity</Label>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {COMPLEXITIES.map((c) => (
                  <Pill
                    key={c}
                    label={c}
                    selected={complexity === c}
                    onClick={() => setComplexity(c)}
                  />
                ))}
              </div>
            </div>

            {/* Budget */}
            <div>
              <Label>Budget (optional)</Label>
              <input
                type="text"
                value={budget}
                onChange={(e) => setBudget(e.target.value)}
                placeholder="₹ or $..."
                style={inputStyle}
              />
            </div>

            {error && (
              <p style={{ color: "#f87171", fontFamily: FONT, fontSize: 13, margin: 0 }}>{error}</p>
            )}

            <motion.button
              whileHover={{ translateY: -1 }}
              whileTap={{ scale: 0.98 }}
              type="submit"
              disabled={loading}
              style={{
                padding: "13px",
                borderRadius: 12,
                fontSize: 14,
                fontFamily: FONT,
                fontWeight: 600,
                background: loading
                  ? "rgba(255,255,255,0.05)"
                  : "linear-gradient(135deg, #9CFCAF, #FFEA71)",
                color: loading ? "rgba(255,255,255,0.3)" : "#000",
                border: "none",
                cursor: loading ? "not-allowed" : "pointer",
                transition: "all 0.2s",
              }}
            >
              {loading ? "Building flow…" : `Generate Flow Plan — ${CREDITS_COST} credits →`}
            </motion.button>
          </motion.form>
        ) : (
          <motion.div
            key="result"
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
          >
            <textarea
              value={result}
              onChange={(e) => setResult(e.target.value)}
              style={{
                width: "100%",
                minHeight: 480,
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: 16,
                padding: "28px",
                fontFamily: FONT,
                fontSize: 14,
                color: "rgba(255,255,255,0.85)",
                lineHeight: 1.8,
                whiteSpace: "pre-wrap",
                marginBottom: 16,
                resize: "vertical",
                outline: "none",
                boxSizing: "border-box",
                caretColor: "#9CFCAF",
              }}
            />

            <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleCopy}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: copied ? "rgba(156,252,175,0.12)" : "rgba(255,255,255,0.06)",
                  border: copied ? "1px solid rgba(156,252,175,0.3)" : "1px solid rgba(255,255,255,0.1)",
                  color: copied ? "#9CFCAF" : "#ffffff",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                {copied ? "Copied!" : "Copy result"}
              </motion.button>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={() => downloadPDF(result, `Flow: ${projectName}`)}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: "rgba(255,255,255,0.04)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  color: "rgba(255,255,255,0.7)",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                Save as PDF
              </motion.button>
              <motion.button
                whileHover={{ translateY: -1 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleStartOver}
                style={{
                  flex: 1,
                  padding: "11px",
                  borderRadius: 10,
                  fontSize: 13,
                  fontFamily: FONT,
                  fontWeight: 600,
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  color: "rgba(255,255,255,0.6)",
                  cursor: "pointer",
                  transition: "all 0.2s",
                }}
              >
                Start over
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
